

def setup_training(self):...

def game_events_occurred(self, old_game_state, self_action, new_game_state, events):...

def end_of_round(self, last_game_state, last_action, events):...

def reward_from_events(self, events) -> float:...